export interface Step {
  phase: string;
  content: string;
  delay: number;
  tool?: string;
}

export interface Scenario {
  id: string;
  name: string;
  icon: string;
  color: string;
  category: string;
  description: string;
  input: string;
}

export const SCENARIOS: Scenario[] = [
  {
    id: "fraud", name: "Fraud Monitoring Agent", icon: "🛡️", color: "from-rose-500 to-orange-500", category: "Security",
    description: "Scans 500 transactions, detects anomalies, flags high-risk transfers, generates alerts",
    input: "Analyze today's transaction batch of 500 payments for fraud patterns. Focus on cross-border transfers above $10,000 and velocity anomalies.",
  },
  {
    id: "compliance", name: "Compliance Agent", icon: "⚖️", color: "from-violet-500 to-indigo-500", category: "Risk & Compliance",
    description: "Runs KYC/AML checks, screens sanctions lists, flags PEPs, generates compliance reports",
    input: "Run full KYC/AML screening on 12 new customer applications. Check OFAC, EU, and UN sanctions lists. Screen for PEPs.",
  },
  {
    id: "reporting", name: "Reporting Agent", icon: "📊", color: "from-emerald-500 to-teal-500", category: "Analytics",
    description: "Aggregates data from 6 sources, identifies trends, generates an executive report",
    input: "Generate the Q1 2026 executive report. Aggregate revenue, transactions, customer metrics, and agent performance data.",
  },
  {
    id: "finance", name: "Finance Agent", icon: "💰", color: "from-amber-500 to-yellow-500", category: "Finance",
    description: "Reconciles 1,200 transactions, matches invoices, identifies discrepancies, generates financial statements",
    input: "Run end-of-day reconciliation for March 24. Match all incoming payments against invoices and flag discrepancies above $50.",
  },
  {
    id: "support", name: "Customer Support Agent", icon: "💬", color: "from-sky-500 to-cyan-500", category: "Operations",
    description: "Triages 85 tickets, routes by urgency, drafts responses, escalates critical issues",
    input: "Process the overnight support queue. Triage all 85 open tickets, draft responses for common issues, and escalate critical items.",
  },
  {
    id: "data", name: "Data Analyst Agent", icon: "🔬", color: "from-fuchsia-500 to-pink-500", category: "Analytics",
    description: "Analyzes customer churn data, identifies at-risk segments, predicts retention probability",
    input: "Analyze customer churn for the last 90 days. Identify at-risk segments, predict next-month churn, and recommend retention actions.",
  },
  {
    id: "operations", name: "Operations Agent", icon: "⚙️", color: "from-slate-400 to-zinc-500", category: "Infrastructure",
    description: "Monitors 24 microservices, detects performance degradation, auto-scales resources, resolves incidents",
    input: "Run system health check across all 24 microservices. Identify performance bottlenecks and auto-remediate where possible.",
  },
  {
    id: "document", name: "Document Processing Agent", icon: "📄", color: "from-orange-500 to-red-500", category: "Automation",
    description: "Processes 150 invoices, extracts data with OCR, validates against POs, routes for approval",
    input: "Process the incoming invoice batch (150 documents). Extract key fields, validate against purchase orders, and route for approval.",
  },
  {
    id: "hr", name: "HR & Onboarding Agent", icon: "👥", color: "from-lime-500 to-green-500", category: "People Ops",
    description: "Onboards 8 new hires, provisions accounts, schedules training, generates offer letters",
    input: "Onboard 8 new employees starting April 1. Provision system access, schedule orientation, assign training modules, and prepare welcome kits.",
  },
  {
    id: "sales", name: "Sales Intelligence Agent", icon: "🎯", color: "from-blue-500 to-indigo-500", category: "Revenue",
    description: "Scores 200 leads, enriches CRM data, identifies upsell opportunities, drafts outreach sequences",
    input: "Score all leads from last week's marketing campaigns. Enrich company data, identify top 20 prospects, and draft personalized outreach.",
  },
  {
    id: "reviews", name: "App Store Review Agent", icon: "📱", color: "from-pink-500 to-rose-500", category: "Customer Experience",
    description: "Processes 47 app reviews, analyzes sentiment, generates professional responses, escalates critical issues to human support",
    input: "Process overnight app store reviews from Google Play and App Store. Analyze sentiment, respond professionally, and escalate critical issues.",
  },
  {
    id: "helpdesk", name: "IT Helpdesk Agent", icon: "🎫", color: "from-cyan-500 to-blue-500", category: "IT Operations",
    description: "Triages 8 IT tickets, auto-resolves password resets and access requests, escalates P1 outages, provisions new hires",
    input: "Process the overnight IT support queue. Auto-resolve common tickets, provision access requests, and escalate critical infrastructure issues.",
  },
  {
    id: "intel", name: "Competitive Intelligence Agent", icon: "🔍", color: "from-amber-500 to-red-500", category: "Strategy",
    description: "Scans 847 sources across 5 competitors, detects funding rounds, pricing changes, product launches, generates strategic recommendations",
    input: "Run a full competitive intelligence scan. Monitor all 5 competitors for product launches, pricing changes, funding rounds, and strategic moves.",
  },
];

export const EXECUTION_SCRIPTS: Record<string, Step[]> = {
  fraud: [
    { phase: "observe", content: "Received transaction batch — 500 payments totaling $2.4M across 23 countries", delay: 600 },
    { phase: "retrieve", content: "Recalled 3 prior fraud patterns from memory: velocity rings in SE Asia, split-transaction evasion on EU corridor, synthetic identity cluster from last week", delay: 800 },
    { phase: "reason", content: "Cross-referencing transaction metadata against known fraud typologies. Applying 5 detection rules: velocity check, amount threshold, geo-risk scoring, device fingerprint anomaly, behavioral deviation...", delay: 1200 },
    { phase: "plan", content: "Execution plan: scan_transactions → calculate_risk_scores → flag_anomalies → cross_reference_watchlists → generate_alerts → compile_report", delay: 500 },
    { phase: "execute", content: "🔍 Tool: query_database({table: 'transactions', filter: {amount_gt: 10000, type: 'cross_border'}})\n→ Found 47 cross-border transfers > $10K", delay: 900, tool: "query_database" },
    { phase: "execute", content: "🔍 Tool: query_database({table: 'transactions', filter: {velocity: 'anomaly'}})\n→ Detected velocity anomaly: 14 transactions from same device in 3 minutes", delay: 700, tool: "query_database" },
    { phase: "execute", content: "⚠️ Tool: calculate_risk_score({transaction_id: 'TXN-28471', amount: 48500, destination: 'high_risk_jurisdiction'})\n→ Risk Score: 0.94 — CRITICAL", delay: 600, tool: "risk_scorer" },
    { phase: "execute", content: "⚠️ Tool: calculate_risk_score({transaction_id: 'TXN-28483', pattern: 'split_transaction'})\n→ Risk Score: 0.87 — 5 transactions of $9,999 from same originator bypassing $10K threshold", delay: 800, tool: "risk_scorer" },
    { phase: "execute", content: "🚨 Tool: send_alert({severity: 'critical', title: 'Suspicious $48.5K wire to sanctioned jurisdiction', transaction: 'TXN-28471'})\n→ Alert ALT-2847 created, escalated to Compliance Team", delay: 500, tool: "send_alert" },
    { phase: "execute", content: "🚨 Tool: send_alert({severity: 'warning', title: 'Velocity ring detected — 14 rapid-fire transactions'})\n→ Alert ALT-2848 created", delay: 500, tool: "send_alert" },
    { phase: "execute", content: "🚨 Tool: send_alert({severity: 'warning', title: 'Structuring detected — split transactions evading $10K threshold'})\n→ Alert ALT-2849 created", delay: 500, tool: "send_alert" },
    { phase: "evaluate", content: "Evaluation: 3 critical/warning alerts generated. 497/500 transactions cleared (99.4%). Confidence: 96%. False positive rate: 0.2%", delay: 700 },
    { phase: "store", content: "Stored 4 new memories: velocity ring pattern (DEV-X91F), structuring pattern (originator ID-8823), high-risk jurisdiction alert, updated risk baseline", delay: 400 },
    { phase: "report", content: "✅ FRAUD SCAN COMPLETE\n\n📊 Summary:\n• 500 transactions scanned ($2.4M total)\n• 497 cleared, 3 flagged\n• 1 CRITICAL: $48.5K wire to sanctioned jurisdiction\n• 2 WARNING: velocity ring + structuring\n• Estimated fraud prevented: $67,483\n\n⏱ 4.2s | 🧠 8 tool calls | 💾 4 memories stored", delay: 0 },
  ],
  compliance: [
    { phase: "observe", content: "Received 12 new customer applications for KYC/AML screening", delay: 600 },
    { phase: "retrieve", content: "Recalled regulatory context: FATF Travel Rule Amendment (effective April 15), AML Directive VI (EU, June 2026). EDD threshold: risk score > 0.6", delay: 800 },
    { phase: "reason", content: "Prioritizing screening by risk level. High-risk jurisdictions require Enhanced Due Diligence. PEP screening uses fuzzy matching at 85% threshold...", delay: 1000 },
    { phase: "plan", content: "Execution plan: verify_documents → screen_sanctions → screen_pep → assess_risk → flag_edd → generate_report", delay: 500 },
    { phase: "execute", content: "📋 Tool: verify_documents({batch: 12, types: ['passport', 'national_id', 'utility_bill']})\n→ 10/12 complete document sets. 2 missing proof of address", delay: 900, tool: "document_verify" },
    { phase: "execute", content: "🔍 Tool: screen_sanctions({lists: ['OFAC', 'EU', 'UN'], customers: 12})\n→ 1 potential match: CUS-003 (Wei Zhang) — OFAC, score: 0.35", delay: 1100, tool: "sanctions_screen" },
    { phase: "execute", content: "🔍 Tool: screen_pep({customers: 12, threshold: 0.85})\n→ 1 match: CUS-007 (Ricardo Oliveira) — Former deputy finance minister, Brazil. Score: 0.91", delay: 900, tool: "pep_screen" },
    { phase: "execute", content: "⚠️ Tool: assess_risk({customer: 'CUS-003', sanctions_match: 0.35})\n→ Risk: HIGH — Requires Enhanced Due Diligence", delay: 600, tool: "risk_assess" },
    { phase: "execute", content: "📧 Tool: send_alert({severity: 'warning', title: 'EDD Required: 2 high-risk customers'})\n→ Notification sent to Compliance Officer", delay: 500, tool: "send_alert" },
    { phase: "evaluate", content: "Evaluation: 8 cleared, 2 require docs resubmission, 2 flagged for EDD. Compliance score: 87/100", delay: 700 },
    { phase: "store", content: "Stored screening results, updated customer risk profiles, logged regulatory citations", delay: 400 },
    { phase: "report", content: "✅ KYC/AML SCREENING COMPLETE\n\n📊 Summary:\n• 12 customers screened\n• 8 CLEARED — ready for onboarding\n• 2 PENDING — missing proof of address\n• 2 HIGH RISK — EDD required\n• Compliance Score: 87/100\n\n⏱ 12.8s | 🧠 7 tool calls | 📋 2 EDD referrals", delay: 0 },
  ],
  reporting: [
    { phase: "observe", content: "Executive report request: Q1 2026 performance across revenue, transactions, customers, and agents", delay: 600 },
    { phase: "retrieve", content: "Recalled Q4 2025 baseline: $2.1M revenue, 38K transactions, 11.2K active customers, 96.1% agent success rate", delay: 800 },
    { phase: "reason", content: "Aggregating from 6 sources: payments DB, customer DB, agent metrics, support tickets, financial ledger, marketing. Calculating QoQ growth...", delay: 1000 },
    { phase: "plan", content: "Execution plan: aggregate_revenue → aggregate_customers → aggregate_agents → identify_trends → compile_report", delay: 500 },
    { phase: "execute", content: "📊 Tool: query_database({source: 'financial_ledger', period: 'Q1-2026'})\n→ Revenue: $2,847,000 (+35.6% QoQ) | Gross Margin: 60.5%", delay: 900, tool: "query_database" },
    { phase: "execute", content: "📊 Tool: query_database({source: 'transactions', period: 'Q1-2026'})\n→ 48,923 transactions (+28.7% QoQ) | Success rate: 99.1%", delay: 700, tool: "query_database" },
    { phase: "execute", content: "📊 Tool: query_database({source: 'customers', period: 'Q1-2026'})\n→ 12,847 active (+14.7% QoQ) | NPS: 72 (+4pts)", delay: 700, tool: "query_database" },
    { phase: "execute", content: "📈 Tool: identify_trends({data: 'all_sources'})\n→ Revenue accelerating (Jan: +8%, Feb: +11%, Mar: +14%). Fraud ROI: 18x", delay: 800, tool: "trend_analyzer" },
    { phase: "execute", content: "📄 Tool: generate_report({title: 'Q1 2026 Executive Report', sections: 6})\n→ RPT-2026-Q1 generated with 12 charts", delay: 600, tool: "report_generator" },
    { phase: "evaluate", content: "Report complete with 6 data sources aggregated. All KPIs positive. Confidence: 98%", delay: 700 },
    { phase: "store", content: "Stored Q1 baseline for future QoQ comparisons", delay: 400 },
    { phase: "report", content: "✅ Q1 2026 EXECUTIVE REPORT\n\n📊 Key Metrics:\n• Revenue: $2,847,000 (+35.6%) 🟢\n• Transactions: 48,923 (+28.7%) 🟢\n• Customers: 12,847 (+14.7%) 🟢\n• Agent Success: 98.7% (+2.6pts) 🟢\n• Cost Saved by AI: $847,000\n• Fraud Prevented: $1.2M (18x ROI)\n\n⏱ 8.1s | 🧠 6 sources | 📊 12 charts", delay: 0 },
  ],
  finance: [
    { phase: "observe", content: "End-of-day reconciliation request — 1,247 transactions for March 24, 2026", delay: 600 },
    { phase: "retrieve", content: "Recalled prior reconciliation patterns: recurring $0.01 rounding discrepancies on FX conversions, pending settlement batch from Deutsche Bank (T+2)", delay: 800 },
    { phase: "reason", content: "Will match all incoming payments against outstanding invoices using amount, reference, and date. FX transactions need rate-adjusted matching. Threshold for manual review: >$50 variance...", delay: 1000 },
    { phase: "plan", content: "Execution plan: fetch_transactions → fetch_invoices → auto_match → identify_discrepancies → reconcile_fx → generate_statement", delay: 500 },
    { phase: "execute", content: "📊 Tool: query_database({table: 'transactions', date: '2026-03-24'})\n→ 1,247 transactions totaling $3,891,204.17", delay: 800, tool: "query_database" },
    { phase: "execute", content: "📊 Tool: query_database({table: 'invoices', status: 'pending'})\n→ 1,189 outstanding invoices totaling $3,847,891.42", delay: 700, tool: "query_database" },
    { phase: "execute", content: "🔗 Tool: auto_match({transactions: 1247, invoices: 1189, tolerance: 0.01})\n→ 1,198 auto-matched (96.1%) | 49 unmatched payments", delay: 1100, tool: "reconciler" },
    { phase: "execute", content: "⚠️ Tool: flag_discrepancy({invoice: 'INV-8847', expected: 24500, received: 24150, delta: -350})\n→ Discrepancy flagged: $350 underpayment on INV-8847 (Globalex Ltd)", delay: 600, tool: "discrepancy_check" },
    { phase: "execute", content: "💱 Tool: reconcile_fx({count: 183, base_currency: 'USD'})\n→ 183 FX transactions reconciled. Rate variance: -$12.40 (within tolerance)", delay: 700, tool: "fx_reconciler" },
    { phase: "execute", content: "📄 Tool: generate_financial_statement({type: 'daily_reconciliation', date: '2026-03-24'})\n→ Statement FS-20260324 generated", delay: 600, tool: "statement_generator" },
    { phase: "evaluate", content: "Evaluation: 96.1% auto-match rate. 1 material discrepancy ($350). FX variance within tolerance. Cash position: $3,891,204.17", delay: 700 },
    { phase: "store", content: "Stored reconciliation results, updated cash position, flagged INV-8847 for collections follow-up", delay: 400 },
    { phase: "report", content: "✅ DAILY RECONCILIATION COMPLETE\n\n📊 Summary:\n• 1,247 transactions reconciled ($3.89M)\n• 96.1% auto-matched (1,198/1,247)\n• 1 discrepancy flagged: $350 underpayment (INV-8847)\n• 183 FX transactions reconciled (-$12.40 variance)\n• 49 unmatched → pending settlement (T+2)\n• Cash Position: $3,891,204.17\n\n⏱ 6.4s | 🧠 6 tool calls | 💰 $3.89M reconciled", delay: 0 },
  ],
  support: [
    { phase: "observe", content: "Overnight support queue: 85 open tickets across 4 channels (email: 52, chat: 18, phone: 9, social: 6)", delay: 600 },
    { phase: "retrieve", content: "Recalled resolution patterns: password reset (avg 1.2 min), billing inquiry (avg 3.4 min), API integration (avg 12 min). Top issue last week: OAuth token expiry", delay: 800 },
    { phase: "reason", content: "Classifying tickets by urgency (P1-P4) and category. P1 tickets (service outage, data loss) get immediate escalation. Common patterns can be auto-resolved with templated responses...", delay: 1000 },
    { phase: "plan", content: "Execution plan: classify_tickets → auto_resolve_common → draft_responses → escalate_critical → update_kb → generate_summary", delay: 500 },
    { phase: "execute", content: "📋 Tool: classify_tickets({count: 85, model: 'support-classifier-v3'})\n→ P1: 3 (critical) | P2: 12 (high) | P3: 41 (medium) | P4: 29 (low)", delay: 900, tool: "ticket_classifier" },
    { phase: "execute", content: "✅ Tool: auto_resolve({tickets: 29, type: 'password_reset, billing_faq, status_inquiry'})\n→ 29 P4 tickets auto-resolved with templated responses (97% accuracy)", delay: 800, tool: "auto_resolver" },
    { phase: "execute", content: "📝 Tool: draft_response({tickets: 41, type: 'P3_medium', include_kb_links: true})\n→ 41 draft responses generated, ready for agent review", delay: 900, tool: "response_drafter" },
    { phase: "execute", content: "🚨 Tool: escalate({ticket: 'TKT-9841', priority: 'P1', issue: 'Production API returning 503 for enterprise client'})\n→ Escalated to on-call engineer. Slack alert sent to #incidents", delay: 600, tool: "escalator" },
    { phase: "execute", content: "🚨 Tool: escalate({ticket: 'TKT-9847', priority: 'P1', issue: 'Data sync failure — 4 hours behind for Acme Corp'})\n→ Escalated with full diagnostic bundle attached", delay: 600, tool: "escalator" },
    { phase: "execute", content: "📚 Tool: update_knowledge_base({new_patterns: 3, articles_updated: 2})\n→ Added solutions for OAuth token rotation, webhook retry backoff, rate limit handling", delay: 500, tool: "kb_updater" },
    { phase: "evaluate", content: "Evaluation: 29 auto-resolved (34%), 41 drafted (48%), 3 escalated (3.5%), 12 routed to specialists. Avg response time: 2.1 min", delay: 700 },
    { phase: "store", content: "Stored ticket patterns, updated resolution templates, logged escalation outcomes", delay: 400 },
    { phase: "report", content: "✅ SUPPORT QUEUE PROCESSED\n\n📊 Summary:\n• 85 tickets triaged across 4 channels\n• 29 auto-resolved (34%) — saved 35 agent-hours\n• 41 responses drafted for review\n• 3 P1 critical escalated to engineering\n• 12 routed to product specialists\n• Avg response time: 2.1 min\n• Customer satisfaction (predicted): 91%\n\n⏱ 3.8s | 🧠 7 tool calls | ⚡ 35 hours saved", delay: 0 },
  ],
  data: [
    { phase: "observe", content: "Churn analysis request — 90-day window across 12,847 active customers and 732 churned accounts", delay: 600 },
    { phase: "retrieve", content: "Recalled previous churn model: top predictors were support ticket frequency (32%), usage drop >40% (28%), billing failures (18%), competitor mentions (12%)", delay: 800 },
    { phase: "reason", content: "Segmenting customer base by product tier, tenure, and engagement score. Will apply gradient boosting model trained on 18 months of churn data. Confidence interval: 95%...", delay: 1100 },
    { phase: "plan", content: "Execution plan: segment_customers → calculate_engagement → run_churn_model → identify_at_risk → generate_retention_actions → compile_report", delay: 500 },
    { phase: "execute", content: "📊 Tool: query_database({table: 'customers', metrics: ['usage', 'tickets', 'billing', 'logins']})\n→ Segmented: Enterprise (847), Pro (4,218), Starter (7,782)", delay: 900, tool: "query_database" },
    { phase: "execute", content: "📈 Tool: calculate_engagement_scores({customers: 12847, window: '90d'})\n→ High: 8,214 (63.9%) | Medium: 3,412 (26.6%) | Low: 1,221 (9.5%)", delay: 800, tool: "engagement_scorer" },
    { phase: "execute", content: "🤖 Tool: run_prediction_model({model: 'churn-gbm-v4', features: 18, customers: 12847})\n→ Predicted next-month churn: 124 accounts (0.97% rate). Precision: 89%, Recall: 91%", delay: 1200, tool: "ml_predictor" },
    { phase: "execute", content: "⚠️ Tool: identify_at_risk({threshold: 0.7, segment: 'enterprise'})\n→ 18 enterprise accounts at risk. Combined ARR: $847,000. Top risk: Meridian Corp (churn prob: 0.89)", delay: 700, tool: "risk_identifier" },
    { phase: "execute", content: "💡 Tool: generate_retention_actions({at_risk: 18, playbooks: ['executive_outreach', 'feature_demo', 'pricing_review']})\n→ 18 personalized retention playbooks generated", delay: 600, tool: "action_generator" },
    { phase: "evaluate", content: "Evaluation: Model accuracy 89%. $847K ARR at risk across 18 enterprise accounts. Retention playbooks estimated to save 72% of at-risk revenue", delay: 700 },
    { phase: "store", content: "Stored updated churn predictions, engagement baselines, and retention playbook outcomes", delay: 400 },
    { phase: "report", content: "✅ CHURN ANALYSIS COMPLETE\n\n📊 Summary:\n• 12,847 customers analyzed (90-day window)\n• Predicted next-month churn: 124 accounts (0.97%)\n• 18 enterprise accounts at risk ($847K ARR)\n• Top risk: Meridian Corp (89% churn probability)\n• 18 retention playbooks generated\n• Estimated save rate: 72% ($610K ARR)\n\n📈 Model: GBM-v4 | Precision: 89% | Recall: 91%\n⏱ 7.2s | 🧠 5 tool calls | 💰 $847K ARR protected", delay: 0 },
  ],
  operations: [
    { phase: "observe", content: "System health check initiated — monitoring 24 microservices across 3 regions (US-East, EU-West, APAC)", delay: 600 },
    { phase: "retrieve", content: "Recalled last incident: payment-service latency spike (March 21, resolved by scaling to 8 replicas). Current SLA target: 99.95% uptime", delay: 800 },
    { phase: "reason", content: "Checking CPU, memory, latency, error rates, and queue depths across all services. Will cross-reference against SLA thresholds and historical baselines. Auto-remediation enabled for known patterns...", delay: 1000 },
    { phase: "plan", content: "Execution plan: check_health → analyze_metrics → detect_anomalies → auto_remediate → verify_fix → generate_report", delay: 500 },
    { phase: "execute", content: "🖥️ Tool: check_service_health({services: 24, regions: ['us-east', 'eu-west', 'apac']})\n→ 22/24 healthy | 2 degraded: payment-service (EU), notification-service (APAC)", delay: 900, tool: "health_checker" },
    { phase: "execute", content: "📊 Tool: analyze_metrics({service: 'payment-service', region: 'eu-west'})\n→ CPU: 94% 🔴 | Memory: 78% 🟡 | P99 latency: 2.8s (SLA: 1s) | Error rate: 2.4%", delay: 800, tool: "metrics_analyzer" },
    { phase: "execute", content: "📊 Tool: analyze_metrics({service: 'notification-service', region: 'apac'})\n→ Queue depth: 12,847 (backlog) | Consumer lag: 45 min | Memory: 91% 🔴", delay: 700, tool: "metrics_analyzer" },
    { phase: "execute", content: "🔧 Tool: auto_scale({service: 'payment-service', region: 'eu-west', from: 4, to: 8})\n→ Scaling from 4 → 8 replicas. ETA: 90 seconds", delay: 1000, tool: "auto_scaler" },
    { phase: "execute", content: "🔧 Tool: restart_consumers({service: 'notification-service', region: 'apac', flush_dlq: true})\n→ 3 consumers restarted, DLQ flushed (847 messages reprocessed)", delay: 800, tool: "service_manager" },
    { phase: "execute", content: "✅ Tool: verify_remediation({services: ['payment-service', 'notification-service']})\n→ payment-service: CPU dropped to 52%, latency: 340ms ✅\n→ notification-service: queue depth: 124, lag: 12s ✅", delay: 700, tool: "health_checker" },
    { phase: "evaluate", content: "Evaluation: 2 incidents auto-remediated. All 24 services now healthy. SLA: 99.97% (above 99.95% target). Zero manual intervention required", delay: 700 },
    { phase: "store", content: "Stored incident patterns, updated scaling thresholds, logged auto-remediation playbook results", delay: 400 },
    { phase: "report", content: "✅ SYSTEM HEALTH CHECK COMPLETE\n\n📊 Summary:\n• 24 microservices checked across 3 regions\n• 22 healthy, 2 auto-remediated:\n  → payment-service (EU): Scaled 4→8 replicas\n  → notification-service (APAC): Consumers restarted\n• SLA: 99.97% (target: 99.95%) ✅\n• Zero manual intervention required\n• MTTR (auto): 90 seconds\n\n⏱ 5.1s | 🧠 6 tool calls | 🔧 2 auto-fixes", delay: 0 },
  ],
  document: [
    { phase: "observe", content: "Incoming invoice batch: 150 documents (PDF: 112, scanned images: 28, email attachments: 10)", delay: 600 },
    { phase: "retrieve", content: "Recalled vendor patterns: Acme Corp uses PO# in footer, Globalex uses reference field, 7 vendors require manual 3-way match. OCR confidence threshold: 92%", delay: 800 },
    { phase: "reason", content: "Processing pipeline: OCR extraction → field validation → PO matching → approval routing. High-value invoices (>$25K) require VP approval. Duplicates detected by invoice# + amount + date hash...", delay: 1000 },
    { phase: "plan", content: "Execution plan: ocr_extract → validate_fields → match_po → detect_duplicates → route_approvals → generate_summary", delay: 500 },
    { phase: "execute", content: "📄 Tool: ocr_extract({documents: 150, engine: 'vision-v3'})\n→ 143 extracted (95.3% success) | 7 low-confidence (manual review queue)", delay: 1100, tool: "ocr_engine" },
    { phase: "execute", content: "✅ Tool: validate_fields({invoices: 143, required: ['vendor', 'amount', 'date', 'invoice_number']})\n→ 138 valid | 5 missing fields (vendor name: 3, date format: 2)", delay: 800, tool: "field_validator" },
    { phase: "execute", content: "🔗 Tool: match_purchase_orders({invoices: 138, tolerance: 2.0})\n→ 124 auto-matched to POs | 14 no matching PO found", delay: 900, tool: "po_matcher" },
    { phase: "execute", content: "⚠️ Tool: detect_duplicates({invoices: 138, hash: 'invoice_number+amount+date'})\n→ 3 potential duplicates detected: INV-44821 ($12,400), INV-44829 ($8,750), INV-44847 ($3,200)", delay: 600, tool: "duplicate_detector" },
    { phase: "execute", content: "📨 Tool: route_approvals({invoices: 124, rules: 'amount_based'})\n→ Auto-approved: 98 (< $5K) | Manager approval: 19 ($5K-$25K) | VP approval: 7 (> $25K)", delay: 700, tool: "approval_router" },
    { phase: "evaluate", content: "Evaluation: 95.3% OCR success rate. 82.7% auto-matched to POs. 3 duplicates caught ($24,350 saved). 98 auto-approved.", delay: 700 },
    { phase: "store", content: "Stored vendor patterns, updated PO matching rules, logged duplicate detection hashes", delay: 400 },
    { phase: "report", content: "✅ INVOICE PROCESSING COMPLETE\n\n📊 Summary:\n• 150 documents processed\n• 143 extracted (95.3% OCR success)\n• 124 matched to purchase orders (82.7%)\n• 3 duplicates caught ($24,350 saved)\n• 98 auto-approved | 19 manager | 7 VP review\n• 7 sent to manual review queue\n\n⏱ 15.3s | 🧠 5 tool calls | 💰 $24,350 duplicates caught", delay: 0 },
  ],
  hr: [
    { phase: "observe", content: "Onboarding request: 8 new employees starting April 1, 2026 across Engineering (4), Sales (2), Finance (1), Operations (1)", delay: 600 },
    { phase: "retrieve", content: "Recalled onboarding playbooks: Engineering requires GitHub, AWS, Jira access. Sales requires CRM + Hubspot. Average onboarding completion: 2.4 days", delay: 800 },
    { phase: "reason", content: "Creating personalized onboarding plans per department. Engineering needs dev environment setup + security training. Sales needs CRM onboarding + product certification. All need compliance training...", delay: 1000 },
    { phase: "plan", content: "Execution plan: provision_accounts → assign_equipment → schedule_training → generate_welcome_kits → notify_managers → create_30_60_90", delay: 500 },
    { phase: "execute", content: "🔑 Tool: provision_accounts({employees: 8, systems: ['email', 'slack', 'jira', 'github', 'aws', 'crm', 'hrms']})\n→ 8 accounts provisioned across 7 systems. MFA enrollment emails sent", delay: 900, tool: "account_provisioner" },
    { phase: "execute", content: "💻 Tool: assign_equipment({employees: 8, specs: 'role_based'})\n→ 4 MacBook Pro M4 (Engineering), 2 ThinkPad (Sales), 2 Standard (Finance, Ops). Shipping confirmed for March 29", delay: 700, tool: "equipment_manager" },
    { phase: "execute", content: "📅 Tool: schedule_training({employees: 8, modules: ['security_awareness', 'compliance', 'product_overview', 'department_specific']})\n→ 32 training sessions scheduled. Avg completion ETA: 2.1 days", delay: 800, tool: "training_scheduler" },
    { phase: "execute", content: "📧 Tool: generate_welcome_kits({employees: 8, include: ['offer_letter', 'handbook', 'org_chart', 'benefits_guide', 'first_week_agenda']})\n→ 8 personalized welcome kits generated and emailed", delay: 600, tool: "document_generator" },
    { phase: "execute", content: "📨 Tool: notify_managers({managers: 5, new_hires: 8, start_date: '2026-04-01'})\n→ Manager notifications sent with onboarding checklists and buddy assignments", delay: 500, tool: "notification_engine" },
    { phase: "execute", content: "📋 Tool: create_30_60_90_plans({employees: 8, template: 'department_specific'})\n→ 8 personalized 30-60-90 day plans created with milestones and review dates", delay: 600, tool: "plan_generator" },
    { phase: "evaluate", content: "Evaluation: 8/8 employees fully provisioned. All systems, training, and documents prepared. Predicted onboarding completion: 2.1 days (vs 2.4 avg)", delay: 700 },
    { phase: "store", content: "Stored onboarding patterns, updated department playbooks, logged equipment assignments", delay: 400 },
    { phase: "report", content: "✅ ONBOARDING PREPARATION COMPLETE\n\n📊 Summary:\n• 8 new hires ready for April 1\n• 56 system accounts provisioned (7 per person)\n• 8 equipment orders placed (shipping March 29)\n• 32 training sessions scheduled\n• 8 welcome kits generated\n• 8 personalized 30-60-90 plans created\n• Predicted onboarding time: 2.1 days\n\n⏱ 5.8s | 🧠 6 tool calls | 👥 8 employees ready", delay: 0 },
  ],
  sales: [
    { phase: "observe", content: "Lead scoring request: 200 leads from last week's campaigns (Webinar: 87, Content Download: 64, Demo Request: 31, Referral: 18)", delay: 600 },
    { phase: "retrieve", content: "Recalled conversion patterns: Demo requests convert at 34%, Referrals at 28%, Webinar at 12%, Content at 8%. Ideal Customer Profile: Series B+, 100-500 employees, fintech/banking vertical", delay: 800 },
    { phase: "reason", content: "Scoring leads using 12 signals: company size, funding stage, industry, job title, engagement depth, website visits, content consumed, technographic fit, intent signals, competitive mentions...", delay: 1100 },
    { phase: "plan", content: "Execution plan: enrich_data → score_leads → segment_tiers → identify_upsells → draft_outreach → generate_pipeline_report", delay: 500 },
    { phase: "execute", content: "🏢 Tool: enrich_company_data({leads: 200, sources: ['clearbit', 'linkedin', 'crunchbase']})\n→ 187 enriched (93.5%). Avg company size: 340 employees. 42 match ICP", delay: 1000, tool: "data_enricher" },
    { phase: "execute", content: "📊 Tool: score_leads({leads: 200, model: 'lead-scorer-v5', signals: 12})\n→ Hot (80+): 23 | Warm (50-79): 68 | Cool (20-49): 72 | Cold (<20): 37", delay: 900, tool: "lead_scorer" },
    { phase: "execute", content: "🎯 Tool: identify_top_prospects({count: 20, sort: 'score_desc', filter: 'icp_match'})\n→ Top prospect: Meridian Capital (score: 94, Series C, 280 employees, banking)\n→ #2: NexaPay (score: 91, Series B, 150 employees, payments)", delay: 800, tool: "prospect_ranker" },
    { phase: "execute", content: "💡 Tool: identify_upsell({existing_customers: true, leads: 200})\n→ 7 leads are existing Starter customers eligible for Pro upgrade. Combined upsell: $148K ARR", delay: 700, tool: "upsell_detector" },
    { phase: "execute", content: "📧 Tool: draft_outreach({leads: 23, type: 'personalized_sequence', steps: 4})\n→ 23 four-step email sequences generated. Personalized by industry, role, and pain point", delay: 800, tool: "outreach_drafter" },
    { phase: "execute", content: "📊 Tool: generate_pipeline_report({leads: 200, segment: 'campaign_source'})\n→ Pipeline value: $2.4M | Weighted: $847K | Projected close: 18 deals in 60 days", delay: 600, tool: "pipeline_reporter" },
    { phase: "evaluate", content: "Evaluation: 23 hot leads identified (11.5%). ICP match rate: 21%. Projected pipeline: $847K weighted. 7 upsell opportunities ($148K ARR)", delay: 700 },
    { phase: "store", content: "Stored lead scores, enrichment data, outreach sequences, updated ICP model weights", delay: 400 },
    { phase: "report", content: "✅ LEAD SCORING & ENRICHMENT COMPLETE\n\n📊 Summary:\n• 200 leads scored and enriched\n• 23 HOT leads (score 80+) — ready for sales\n• 42 ICP matches (21% match rate)\n• 7 upsell opportunities ($148K ARR)\n• Pipeline value: $2.4M | Weighted: $847K\n• 23 personalized outreach sequences drafted\n• Projected: 18 deals closing in 60 days\n\n⏱ 9.4s | 🧠 6 tool calls | 💰 $847K pipeline", delay: 0 },
  ],
  reviews: [
    { phase: "observe", content: "Overnight review queue: 47 new reviews across Google Play (28) and App Store (19). Rating distribution: ★★★★★ 18, ★★★★ 9, ★★★ 7, ★★ 5, ★ 8", delay: 600 },
    { phase: "retrieve", content: "Recalled prior review patterns: v3.2.1 introduced crash on Android 13 (mentioned in 6 reviews last week). Common praise: AI spending assistant. Known escalation: legal threat from user 'S.Mitchell' (case #SUP-8847)", delay: 800 },
    { phase: "reason", content: "Prioritizing by sentiment: 8 critical (1-star) reviewed first for escalation. Categorizing by topic: Performance (12), Praise (18), Feature Request (7), Bug Report (5), Billing (3), Authentication (2). Applying response templates per category with personalization...", delay: 1200 },
    { phase: "plan", content: "Execution plan: fetch_reviews → analyze_sentiment → categorize_topics → generate_responses → escalate_critical → post_responses → update_crm → generate_insights", delay: 500 },
    { phase: "execute", content: "📱 Tool: fetch_reviews({platforms: ['google_play', 'app_store'], since: '24h'})\n→ 47 reviews fetched. Avg rating: 3.6 ★ (down from 4.1 last week)", delay: 800, tool: "review_fetcher" },
    { phase: "execute", content: "🔍 Tool: analyze_sentiment({reviews: 47, model: 'sentiment-v4'})\n→ Positive: 18 (38%) | Neutral: 12 (26%) | Negative: 9 (19%) | Critical: 8 (17%)", delay: 900, tool: "sentiment_analyzer" },
    { phase: "execute", content: "🚨 Tool: escalate_to_human({review: 'REV-001', author: 'Sarah Mitchell', issue: 'Data loss + legal threat', priority: 'URGENT'})\n→ Ticket #SUP-8847 created. Assigned to Senior Support Lead. Manager notified via Slack", delay: 700, tool: "escalation_router" },
    { phase: "execute", content: "🚨 Tool: escalate_to_human({review: 'REV-008', author: 'Tom Anderson', issue: 'Unauthorized transactions — security breach', priority: 'URGENT'})\n→ Ticket #SEC-1142 created. Fraud team notified. Account flagged for review", delay: 700, tool: "escalation_router" },
    { phase: "execute", content: "📝 Tool: generate_responses({reviews: 47, templates: 'category_based', personalize: true})\n→ 47 professional responses generated. Avg length: 127 words. Tone: empathetic, solution-oriented", delay: 1100, tool: "response_generator" },
    { phase: "execute", content: "📤 Tool: post_responses({platform: 'google_play', responses: 28})\n→ 28 responses posted to Google Play Developer Console", delay: 600, tool: "review_responder" },
    { phase: "execute", content: "📤 Tool: post_responses({platform: 'app_store', responses: 19})\n→ 19 responses posted to App Store Connect", delay: 600, tool: "review_responder" },
    { phase: "execute", content: "📊 Tool: generate_insights({reviews: 47, compare: 'last_7_days'})\n→ Trending issue: v3.2.1 crash on Android 13 (mentioned 6x). Feature demand: dark mode (4x). Sentiment trending down -0.5 pts", delay: 800, tool: "insight_generator" },
    { phase: "evaluate", content: "Evaluation: 47/47 reviews processed (100%). 3 escalated to human support (6.4%). Response tone verified: professional, empathetic. Avg response time: 2.3 min vs industry avg 24h", delay: 700 },
    { phase: "store", content: "Stored sentiment trends, updated response templates, logged escalation patterns, flagged v3.2.1 crash for engineering priority", delay: 400 },
    { phase: "report", content: "✅ APP STORE REVIEW PROCESSING COMPLETE\n\n📊 Summary:\n• 47 reviews processed (Google Play: 28, App Store: 19)\n• Avg Rating: 3.6 ★ (↓0.5 from last week)\n• Sentiment: 38% positive, 26% neutral, 19% negative, 17% critical\n• 47 professional responses generated & posted\n• 3 escalated to human support (URGENT)\n  → Sarah Mitchell: Data loss + legal threat\n  → Tom Anderson: Unauthorized transactions\n  → Emily Watson: Account lockout (3 days)\n• 🔔 Trending issue: v3.2.1 Android 13 crash\n• 🌙 Top feature request: Dark mode (4 mentions)\n• Response time: 2.3 min (industry avg: 24h)\n\n⏱ 8.7s | 🧠 8 tool calls | 📱 47 responses posted", delay: 0 },
  ],
  helpdesk: [
    { phase: "observe", content: "IT ticket queue: 8 open tickets across 6 departments. Priority breakdown: P1: 1, P2: 2, P3: 4, P4: 1", delay: 600 },
    { phase: "retrieve", content: "Recalled resolution patterns: password resets avg 47s (auto-resolvable), VPN drops on Comcast = DNS issue (TKT-3847), Jenkins OOM threshold = 4GB (incident last month)", delay: 800 },
    { phase: "reason", content: "Classifying tickets by auto-resolution eligibility. P4 password resets and P3 access requests with manager approval can be fully automated. P1 service outage needs emergency remediation + escalation. P2 hardware needs vendor coordination...", delay: 1100 },
    { phase: "plan", content: "Execution plan: classify_tickets → auto_resolve_p4 → provision_access → deploy_software → diagnose_vpn → escalate_p1 → provision_new_hires → update_permissions → generate_report", delay: 500 },
    { phase: "execute", content: "🔑 Tool: reset_password({user: 'jessica.park', system: 'salesforce'})\n→ Password reset. Temp credentials sent via encrypted email. SSO sync verified.\n✅ TKT-4001 auto-resolved in 47 seconds", delay: 700, tool: "password_reset" },
    { phase: "execute", content: "🔐 Tool: provision_iam({user: 'raj.patel', project: 'orion', services: ['s3', 'lambda', 'dynamodb']})\n→ IAM role assigned. MFA enrollment required within 24h.\n✅ TKT-4002 auto-resolved. Manager approval verified", delay: 700, tool: "iam_provisioner" },
    { phase: "execute", content: "💾 Tool: deploy_software({asset: 'FIN-LP-0847', package: 'tableau-desktop-2024.1', method: 'SCCM'})\n→ Deployment queued. ETA: 2 hours. License activated (48/50 seats).\n✅ TKT-4003 auto-resolved", delay: 600, tool: "software_deploy" },
    { phase: "execute", content: "🌐 Tool: diagnose_vpn({user: 'david.kim', logs: '7d'})\n→ Root cause: split-tunnel DNS conflict with Comcast. Fix applied: forced internal DNS resolver.\n✅ TKT-4004 resolved. Monitoring 24h", delay: 800, tool: "vpn_diagnostics" },
    { phase: "execute", content: "🚨 Tool: emergency_remediate({service: 'jenkins-master', action: 'kill_zombie_jobs+increase_heap'})\n→ 47 zombie jobs killed (3.8GB freed). Heap 4GB→8GB. Jenkins online. 14 engineers unblocked.\n⚠️ TKT-4006 escalated to DevOps On-Call for root cause analysis", delay: 1000, tool: "incident_response" },
    { phase: "execute", content: "👤 Tool: onboard_employees({count: 3, systems: ['email', 'slack', 'github', 'jira']})\n→ 12 accounts created. 3 laptops queued. Welcome emails sent.\n✅ TKT-4007 auto-resolved — 3 employees ready for Day 1", delay: 700, tool: "onboarding_engine" },
    { phase: "execute", content: "🔒 Tool: update_ad_groups({user: 'chris.johnson', remove: ['compliance-rw'], add: ['legal-rw']})\n→ AD groups updated. File server access confirmed.\n✅ TKT-4008 auto-resolved", delay: 600, tool: "ad_manager" },
    { phase: "evaluate", content: "Evaluation: 6/8 auto-resolved (75%). 1 assigned to Hardware Team (MacBook repair). 1 escalated to DevOps (P1 Jenkins outage). Avg resolution: 1.2 min. Zero human intervention for auto-resolved tickets", delay: 700 },
    { phase: "store", content: "Stored resolution patterns: Comcast VPN fix, Jenkins OOM threshold, new hire playbook. Updated knowledge base with 3 new articles", delay: 400 },
    { phase: "report", content: "✅ IT HELPDESK QUEUE PROCESSED\n\n📊 Summary:\n• 8 tickets triaged across 6 departments\n• 6 auto-resolved (75%) — zero human intervention\n• 1 assigned to Hardware Team (MacBook repair)\n• 1 P1 escalated to DevOps (Jenkins OOM — 14 engineers unblocked)\n• Avg resolution time: 1.2 min\n• 3 new hire accounts provisioned (12 systems)\n• Cost saved: ~$1,200 (8 hours of IT staff time)\n\n⏱ 6.1s | 🧠 7 tool calls | ⚡ 75% auto-resolution rate", delay: 0 },
  ],
  intel: [
    { phase: "observe", content: "Competitive intelligence scan initiated — monitoring 5 competitors across 847 sources: news, blogs, job boards, social media, SEC filings, app stores", delay: 600 },
    { phase: "retrieve", content: "Recalled previous intel: NexaFlow raised $16M Series A (6 months ago). AutoPilot.io pricing was $799/mo enterprise. AgentForge had no data partnerships. Our market position: strong on security, growing on analytics", delay: 800 },
    { phase: "reason", content: "Scanning for 6 signal types: funding rounds, pricing changes, product launches, partnerships, hiring patterns, press mentions. Will cross-reference against our feature matrix and pricing to assess competitive impact...", delay: 1100 },
    { phase: "plan", content: "Execution plan: scan_news → scan_jobs → scan_funding → analyze_pricing → scan_launches → scan_partnerships → generate_battle_cards → generate_alerts → compile_report", delay: 500 },
    { phase: "execute", content: "📰 Tool: scan_sources({competitors: 5, sources: 847, period: '72h'})\n→ 12 relevant articles found. 147 job postings detected across competitors", delay: 900, tool: "source_scanner" },
    { phase: "execute", content: "💰 Tool: detect_funding({sources: ['crunchbase', 'pitchbook', 'sec']})\n→ ALERT: NexaFlow AI raised $42M Series B (Sequoia-led). Total raised: $58M. Plans to hire 80 engineers", delay: 800, tool: "funding_monitor" },
    { phase: "execute", content: "💲 Tool: analyze_pricing({competitors: 5, compare: 'our_plans'})\n→ ALERT: AutoPilot.io cut enterprise pricing 35% ($799→$519/mo). Now $20/mo cheaper than our Pro tier", delay: 800, tool: "pricing_analyzer" },
    { phase: "execute", content: "🚀 Tool: detect_launches({sources: ['product_hunt', 'github', 'blogs']})\n→ NexaFlow launched 'ReasonEngine' (multi-step reasoning). BotBuilder launched free tier (2 agents)", delay: 700, tool: "launch_detector" },
    { phase: "execute", content: "🤝 Tool: detect_partnerships({sources: ['press', 'linkedin']})\n→ AgentForge partnered with Snowflake for data integrations. Joint webinar April 15", delay: 600, tool: "partnership_monitor" },
    { phase: "execute", content: "📋 Tool: update_battle_cards({competitors: ['nexaflow', 'autopilot'], intel: 'latest'})\n→ 2 sales battle cards updated. Win/loss talking points refreshed", delay: 700, tool: "battle_card_gen" },
    { phase: "execute", content: "⚠️ Tool: generate_strategic_alerts({priority: 'high', recipients: ['ceo', 'vp_product', 'head_sales']})\n→ 3 high-priority alerts sent to leadership: funding, pricing, product launch", delay: 600, tool: "alert_generator" },
    { phase: "evaluate", content: "Evaluation: 7 competitive signals detected. 3 high-impact, 3 medium, 1 low. NexaFlow is primary threat (funding + product). AutoPilot.io pricing pressure requires response", delay: 700 },
    { phase: "store", content: "Stored competitive landscape snapshot, updated threat matrix, logged pricing history, saved battle cards for sales team", delay: 400 },
    { phase: "report", content: "✅ COMPETITIVE INTELLIGENCE SCAN COMPLETE\n\n📊 Summary:\n• 847 sources scanned across 5 competitors\n• 7 signals detected (3 high, 3 medium, 1 low)\n\n🚨 HIGH-IMPACT ALERTS:\n1. NexaFlow raised $42M Series B — expanding into compliance\n2. AutoPilot.io cut enterprise pricing 35% — now $519/mo\n3. NexaFlow launched ReasonEngine — multi-step reasoning\n\n⚠️ MEDIUM ALERTS:\n4. AgentForge × Snowflake partnership\n5. AutoPilot.io hiring 12 security engineers\n6. WorkflowAI in Gartner RPA quadrant\n\n📋 2 battle cards updated for sales team\n⏱ 7.8s | 🧠 7 tool calls | 🔍 847 sources scanned", delay: 0 },
  ],
};
