/**
 * White-Label & Custom Branding
 *
 * Per-tenant theming, custom domains, branded emails,
 * logo management, and custom report headers.
 */

// ─── Types ─────────────────────────────────

export interface BrandConfig {
  id: string;
  tenantId: string;
  companyName: string;
  logoUrl: string | null;
  faviconUrl: string | null;
  theme: ThemeConfig;
  customDomain: CustomDomain | null;
  emailBranding: EmailBranding;
  reportBranding: ReportBranding;
  loginPage: LoginPageConfig;
  createdAt: number;
  updatedAt: number;
}

export interface ThemeConfig {
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  fontFamily: string;
  borderRadius: string;
  darkMode: boolean;
}

export interface CustomDomain {
  domain: string;
  status: "pending_verification" | "verified" | "failed";
  verificationRecord: { type: string; name: string; value: string };
  sslStatus: "pending" | "active" | "expired";
  configuredAt: number;
}

export interface EmailBranding {
  fromName: string;
  fromEmail: string;
  replyTo: string;
  headerHtml: string;
  footerHtml: string;
  accentColor: string;
}

export interface ReportBranding {
  headerLogoUrl: string | null;
  companyName: string;
  tagline: string;
  footerText: string;
  includeWatermark: boolean;
}

export interface LoginPageConfig {
  title: string;
  subtitle: string;
  backgroundImageUrl: string | null;
  showPoweredBy: boolean;
  customCss: string;
}

// ─── Default Theme ─────────────────────────

const DEFAULT_THEME: ThemeConfig = {
  primaryColor: "#2563eb",
  secondaryColor: "#7c3aed",
  accentColor: "#0ea5e9",
  backgroundColor: "#ffffff",
  textColor: "#1e293b",
  fontFamily: "Inter, system-ui, sans-serif",
  borderRadius: "8px",
  darkMode: false,
};

// ─── Engine ────────────────────────────────

export class WhiteLabelEngine {
  private configs = new Map<string, BrandConfig>();
  private domainIndex = new Map<string, string>(); // domain → tenantId

  /**
   * Set up or update branding for a tenant
   */
  configure(params: {
    tenantId: string;
    companyName: string;
    logoUrl?: string;
    faviconUrl?: string;
    theme?: Partial<ThemeConfig>;
    emailBranding?: Partial<EmailBranding>;
    reportBranding?: Partial<ReportBranding>;
    loginPage?: Partial<LoginPageConfig>;
  }): BrandConfig {
    const existing = this.configs.get(params.tenantId);
    const now = Date.now();

    const config: BrandConfig = {
      id: existing?.id || `brand_${now}_${Math.random().toString(36).slice(2, 6)}`,
      tenantId: params.tenantId,
      companyName: params.companyName,
      logoUrl: params.logoUrl || existing?.logoUrl || null,
      faviconUrl: params.faviconUrl || existing?.faviconUrl || null,
      theme: { ...DEFAULT_THEME, ...existing?.theme, ...params.theme },
      customDomain: existing?.customDomain || null,
      emailBranding: {
        fromName: params.companyName,
        fromEmail: `noreply@${params.companyName.toLowerCase().replace(/\s+/g, "")}.com`,
        replyTo: `support@${params.companyName.toLowerCase().replace(/\s+/g, "")}.com`,
        headerHtml: "",
        footerHtml: `<p>&copy; ${new Date().getFullYear()} ${params.companyName}. All rights reserved.</p>`,
        accentColor: params.theme?.primaryColor || DEFAULT_THEME.primaryColor,
        ...existing?.emailBranding,
        ...params.emailBranding,
      },
      reportBranding: {
        headerLogoUrl: params.logoUrl || null,
        companyName: params.companyName,
        tagline: "",
        footerText: `Generated by ${params.companyName}`,
        includeWatermark: false,
        ...existing?.reportBranding,
        ...params.reportBranding,
      },
      loginPage: {
        title: `Welcome to ${params.companyName}`,
        subtitle: "Sign in to your AI agent platform",
        backgroundImageUrl: null,
        showPoweredBy: true,
        customCss: "",
        ...existing?.loginPage,
        ...params.loginPage,
      },
      createdAt: existing?.createdAt || now,
      updatedAt: now,
    };

    this.configs.set(params.tenantId, config);
    return config;
  }

  /**
   * Set up a custom domain
   */
  setupCustomDomain(tenantId: string, domain: string): CustomDomain | null {
    const config = this.configs.get(tenantId);
    if (!config) return null;

    // Check domain isn't taken
    const existingTenant = this.domainIndex.get(domain);
    if (existingTenant && existingTenant !== tenantId) return null;

    const customDomain: CustomDomain = {
      domain,
      status: "pending_verification",
      verificationRecord: {
        type: "CNAME",
        name: `_agentplatform.${domain}`,
        value: `verify.agentplatform.com`,
      },
      sslStatus: "pending",
      configuredAt: Date.now(),
    };

    config.customDomain = customDomain;
    config.updatedAt = Date.now();
    this.domainIndex.set(domain, tenantId);
    return customDomain;
  }

  /**
   * Verify a custom domain
   */
  verifyDomain(tenantId: string): CustomDomain | null {
    const config = this.configs.get(tenantId);
    if (!config?.customDomain) return null;

    // In production, would check DNS records
    config.customDomain.status = "verified";
    config.customDomain.sslStatus = "active";
    config.updatedAt = Date.now();
    return config.customDomain;
  }

  /**
   * Get branding config for a tenant
   */
  getConfig(tenantId: string): BrandConfig | null {
    return this.configs.get(tenantId) || null;
  }

  /**
   * Get tenant by custom domain
   */
  getTenantByDomain(domain: string): string | null {
    return this.domainIndex.get(domain) || null;
  }

  /**
   * Generate CSS variables from theme
   */
  generateCssVariables(tenantId: string): string | null {
    const config = this.configs.get(tenantId);
    if (!config) return null;

    const t = config.theme;
    return `:root {
  --color-primary: ${t.primaryColor};
  --color-secondary: ${t.secondaryColor};
  --color-accent: ${t.accentColor};
  --color-background: ${t.backgroundColor};
  --color-text: ${t.textColor};
  --font-family: ${t.fontFamily};
  --border-radius: ${t.borderRadius};
  --color-scheme: ${t.darkMode ? "dark" : "light"};
}`;
  }

  /**
   * Remove custom domain
   */
  removeDomain(tenantId: string): boolean {
    const config = this.configs.get(tenantId);
    if (!config?.customDomain) return false;
    this.domainIndex.delete(config.customDomain.domain);
    config.customDomain = null;
    config.updatedAt = Date.now();
    return true;
  }

  /**
   * Reset to default theme
   */
  resetTheme(tenantId: string): ThemeConfig | null {
    const config = this.configs.get(tenantId);
    if (!config) return null;
    config.theme = { ...DEFAULT_THEME };
    config.updatedAt = Date.now();
    return config.theme;
  }
}

// ─── Singleton ─────────────────────────────

let engine: WhiteLabelEngine | null = null;
export function getWhiteLabelEngine(): WhiteLabelEngine {
  if (!engine) engine = new WhiteLabelEngine();
  return engine;
}
